# Generated by Django 4.0 on 2023-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='createdBy',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
