# Generated by Django 4.0 on 2023-10-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_incidentreport_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
