# Generated by Django 4.0 on 2023-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_incidentreport_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='incident_reports/'),
        ),
    ]
