# Generated by Django 4.2.6 on 2023-10-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_incidentreport_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='imageUrl',
            new_name='imageUrls',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(),
        ),
    ]
