# Generated by Django 4.2.6 on 2023-10-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_imageurl_incidentreport_imageurls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrls',
            field=models.JSONField(default=list),
        ),
    ]
