# Generated by Django 4.2.6 on 2023-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_incidentreport_imageurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrls',
            field=models.URLField(),
        ),
    ]
