# Generated by Django 4.2.6 on 2023-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_incidentreport_imageurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrls',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
