# Generated by Django 4.2.6 on 2023-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_incidentreport_imageurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrls',
            field=models.ImageField(default=1, upload_to='incident_reports/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageURL',
        ),
    ]
