# Generated by Django 4.2.6 on 2023-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_alter_incidentreport_imageurls_delete_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='imageUrls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
