# Generated by Django 4.2.6 on 2023-11-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_incidentreport_imageurls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.incidentreport')),
            ],
        ),
    ]
