# Generated by Django 4.2.6 on 2023-11-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageURL',
        ),
    ]
