# Generated by Django 4.2.6 on 2023-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSigns',
            fields=[
                ('roadsign_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='roadsign_images/')),
            ],
            options={
                'db_table': 'RoadSigns',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
