# Generated by Django 4.2.6 on 2023-11-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_remove_contact_contact_id_contact_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadSigns',
            new_name='RoadSign',
        ),
    ]
